import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Download, MapPin, ShieldCheck } from "lucide-react";
import { profile, skills } from "@/data/profile";
import { featuredProjects, liveProjects, projects } from "@/data/projects";
import { currentResearch } from "@/data/research";
import { ProjectCard } from "@/components/project-card";

export const metadata = { alternates: { canonical: "/" } };
export default function Home() {
  const featured = featuredProjects.slice(0, 4);
  return <>
    <section className="section mobile-home-hero overflow-hidden"><div className="container grid items-center gap-6 sm:gap-8 lg:grid-cols-[1.15fr_.85fr] lg:gap-16">
      <div><div className="chip"><ShieldCheck aria-hidden size={14}/> {profile.availability}</div><p className="eyebrow mt-5 sm:mt-8">BANKING · DATA SCIENCE · APPLIED AI</p><h1 className="display mt-2 font-black sm:mt-4">Sithan <span className="text-[var(--accent)]">Sitana</span></h1><h2 className="mt-4 max-w-2xl text-xl font-bold leading-snug sm:mt-6 md:text-2xl">{profile.headline}</h2><p className="mt-3 max-w-[58ch] text-base leading-7 muted md:hidden">I combine banking experience with data science and applied AI to build practical analytics, machine-learning, and decision-support applications.</p><p className="mt-5 hidden max-w-[62ch] text-lg leading-8 muted md:block">I combine banking experience, data science, and applied AI to build practical analytics, machine-learning solutions, and decision-support applications grounded in clear methods and reviewable evidence.</p><div className="mobile-hero-actions mt-5 flex flex-col gap-2 sm:mt-7 sm:flex-row sm:flex-wrap sm:gap-3"><Link className="btn btn-primary sm:!w-auto" href="/projects">View Projects <ArrowRight aria-hidden size={17}/></Link><Link className="btn sm:!w-auto" href="/applications">Launch Applications</Link><a className="btn sm:!w-auto" href="/cv.pdf" download>Download CV <Download aria-hidden size={17}/></a></div><p className="mt-4 flex items-center gap-2 text-sm muted sm:mt-5"><MapPin aria-hidden size={16}/>{profile.location}</p></div>
      <div className="relative mx-auto w-full max-w-[20rem] p-1 md:max-w-[21rem] lg:max-w-[27rem] lg:p-2"><div aria-hidden="true" className="absolute inset-0 rotate-[0.75deg] rounded-[1.5rem] border border-[var(--accent)]/30 bg-[var(--accent-soft)] lg:rounded-[1.75rem]" style={{boxShadow:"var(--portrait-shadow)"}}/><div className="relative rounded-[1.3rem] border border-[var(--line)] bg-[var(--surface)] p-0.5 lg:rounded-[1.45rem] lg:p-1"><div className="relative aspect-[4/5] overflow-hidden rounded-[1.1rem] bg-[var(--surface-soft)] lg:rounded-[1.2rem]"><Image src="/professional-photo.jpg" alt="Professional portrait of Sithan Sitana" fill priority quality={90} sizes="(max-width: 640px) 320px, (max-width: 1024px) 336px, 432px" className="object-cover" style={{objectPosition:"50% 18%"}}/></div></div></div>
    </div><div className="mobile-metrics container mt-6 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--line)] sm:mt-9 lg:mt-14 lg:grid-cols-4">{[["Nearly 6 Years","≈6 years","Banking experience","Banking-industry experience"],["Master’s Student","Master’s","Data Science","Data Science student at ITC"],[`${projects.length} Projects`,String(projects.length),"Portfolio projects","Applied data science projects"],[`${liveProjects.length} Live Apps`,String(liveProjects.length),"Deployed applications","Live Streamlit applications"]].map(([mobileValue,value,mobileLabel,label])=><div className="bg-[var(--surface)] p-3.5 sm:p-5" key={label}><p className="text-base font-black sm:hidden">{mobileValue}</p><p className="hidden text-xl font-black sm:block">{value}</p><p className="mt-0.5 text-xs muted sm:mt-1 sm:text-sm"><span className="sm:hidden">{mobileLabel}</span><span className="hidden sm:inline">{label}</span></p></div>)}</div></section>
    <section className="py-8 sm:py-10"><div className="container"><div className="card grid items-center gap-6 p-6 sm:p-8 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-3"><p className="eyebrow">Current Research</p><span className="chip">{currentResearch.status}</span></div><h2 className="mt-3 max-w-[34ch] text-2xl font-black leading-tight tracking-[-.035em] sm:text-3xl">{currentResearch.title}</h2><p className="mt-3 max-w-[70ch] leading-7 muted">{currentResearch.shortDescription}</p></div><Link className="btn btn-primary lg:!w-auto" href="/research#current-research">View Research <ArrowRight aria-hidden size={17}/></Link></div></div></section>
    <section className="section border-y border-[var(--line)] bg-[var(--surface-soft)]/40"><div className="container"><div className="flex items-end justify-between gap-6"><div><p className="eyebrow">Selected work</p><h2 className="title mt-3 font-black">Banking and Khmer NLP solutions with inspectable source.</h2></div><Link className="hidden font-bold text-[var(--accent)] md:block" href="/projects">Explore all projects →</Link></div>{featured.length ? <div className="mt-10 grid gap-6 md:grid-cols-2">{featured.map((project,index)=><ProjectCard key={project.id} project={project} priority={index===0}/>)}</div> : <div className="card mt-10 p-8 text-center"><h3 className="font-black">No featured projects selected</h3><p className="mt-2 muted">Mark a verified project as featured in the shared project data.</p></div>}<Link className="btn mt-6 md:hidden" href="/projects">Explore all projects</Link></div></section>
    <section className="section"><div className="container grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Working approach</p><h2 className="title mt-3 font-black">Technical work with business and research discipline.</h2><p className="mt-6 max-w-xl text-lg leading-8 muted">Civil engineering trained me to think in systems. Banking taught me how service, product, and operational decisions meet real customers. Data science gives me the tools to investigate those systems with evidence.</p></div><div className="grid gap-4 sm:grid-cols-2">{Object.entries(skills).map(([group,items])=><article className="card p-5" key={group}><h3 className="font-black">{group}</h3><p className="mt-2 text-sm leading-6 muted">{items.join(" · ")}</p></article>)}</div></div></section>
    <section className="section bg-[var(--surface)]"><div className="container text-center"><p className="eyebrow">Professional and academic profile</p><h2 className="title mx-auto mt-3 font-black">Explore the evidence behind the profile.</h2><p className="mx-auto mt-5 max-w-2xl leading-7 muted">Review deployed applications, public repositories, project methods, professional experience, and clearly labeled academic work.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/applications" className="btn btn-primary sm:!w-auto">Live applications</Link><Link href="/research" className="btn sm:!w-auto">Research profile</Link></div></div></section>
  </>;
}
